- name: Create /etc/fdfs directory if it does not exist
  file:
    path: "{{client_dir}}"
    state: directory
    mode: '0755'

- name: config client.conf
  template:
    src: client.conf.sample
    dest: /etc/fdfs/client.conf
